### ISSUE TITLE
Decide how to handle French names

### ISSUE THREAD

**Issue by talllguy** [osmlab/bmorebuildings#2]
For street names like LASALLE, is the proper casing LaSalle or Lasalle?

**Comment by talllguy** [comment]
Update: Need to ask the data owner about this.

**Comment by seanflaherty** [comment]
I've done a quick Google search of "Lasalle Baltimore City" without quotes, and all the references to the Baltimore City Street name only capitalize the first letter l (Lasalle.)  The Wikipedia "La Salle" disambiguation page (http://en.wikipedia.org/wiki/La_Salle) lists a few entries as "Lasalle", so I think that casing is not incorrect generally. 

Based on this research, I would say Lasalle is the proper casing for the Baltimore street name.  

This is the type of research that could be done.  Another set of much more in-depth resources is at: http://baltimorecityhistory.net/research-at-the-baltimore-city-archives/the-geography-of-baltimore-city-sources/

I'm not sure what would be considered definitive research, or who would/should make a final decision on the proper spelling/casing of street names.  

Editied to add:  You could just go with how Google maps has the casing, which is "Lasalle."  Of course I could imagine the case where Baltimore City has 2 streets named "Lasalle Ave", "LaSalle Street."  
There could also be the case of "La Salle Court" (with a space), which I would argue is a different name and should be treated differently.  

I also looked at a file available at Open Baltimore (https://data.baltimorecity.gov/) called "Street Centerlines - Shape" (https://data.baltimorecity.gov/Geographic/Street-Centerlines-Shape/if4d-h57f) which lists in a dbf file which lists street names and there is only one "LASALLE."  This doesn't help us with casing because all the data is in "ALL-CAPS.'  It also says it was last updated in 2008, so it seems to be not current.

**Comment by talllguy** [comment]
@seanflaherty thanks for the research and comment! As I just mentioned on twitter, for this particular issue I've emailed our contact Jim Garcia at MOIT to get to the bottom of this. According to him, the spelling of street names is in ALL CAPS in all their data, as well as the signs, so it is not immediately clear how it should be spelled.

If the city doesn't find out anything, I think your suggestion of using "Lasalle" should be good enough. In the future, the city may want to use mixed case street name signs and so at that point, they may want to look deeper into it. I think the ultimate best source would be a record plat, if it exists.

**Comment by talllguy** [comment]
![2015-01-26 12_21_49-mdlandrec_ view land record](https://cloud.githubusercontent.com/assets/1827881/5904392/03271ade-a556-11e4-81d2-2295c9b18efb.png)

I pulled a random deed along the street and in this case they're using the _LaSalle_ casing. It doesn't appear to be a part of a plat.

**Comment by talllguy** [comment]
Found one!
![2015-01-26 12_27_44-dsl01710-1 jpg 3446x2946](https://cloud.githubusercontent.com/assets/1827881/5904483/c873aa00-a556-11e4-9827-15b438699406.png)
[source](http://plato.mdarchives.state.md.us/msa/stagser/s1500/s1529/cfm/dsp_unit.cfm?county=bc&qualifier=C&series=2827&unit=1710&p_ds_value=1&p_ms_value=0)

**Comment by talllguy** [comment]
Talked with @jgeo64 about this and basically it is up to us. So I think the way the plats and deeds have it should be used.
